name: Build Linux
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  # Note that
  # https://github.com/subosito/flutter-action/issues/345
  build_linux:
    name: Build application - ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - platform: x64
            runner: ubuntu-latest
#          - platform: arm64
#            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout application
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Common setup
        uses: ./.github/actions/flutter-common

      # Compare with list of available packages on the runner:
      # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
      - name: Build application for linux
        run: |
          sudo apt update
          sudo apt install -y pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev --no-install-recommends
          flutter build linux --release
          tar -zcvf linux-${{ matrix.platform }}.tar.gz build/linux/${{ matrix.platform }}/release/bundle

      - uses: actions/upload-artifact@v4
        with:
          name: builds-linux
          path: |
            linux-${{ matrix.platform }}.tar.gz

# cp build/linux/${{ matrix.platform }}/release/bundle/wger build/linux/${{ matrix.platform }}/release/bundle/wger-linux-${{ matrix.platform }}