name: TEST flathub
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to tag and release (X.Y.Z)
        required: true
        type: string

jobs:

   generate_flathub_manifest:
    runs-on: ubuntu-latest
    name: Upload flathub manifest (TEST)
    steps:
      - name: Checkout application
        uses: actions/checkout@v4
        with:
          repository: rolandgeider/rge-de.wger.flutter
          ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
#          repository: wger-project/de.wger.flutter
          ref: feature/automate-build
#          path: flathub
          persist-credentials: false


      - name: Bump version in manifest
        run: |
               pip install pyyaml toml
               git clone https://github.com/TheAppgineer/flatpak-flutter.git --branch 0.6.0 ../flatpak-flutter
               python bump-wger-version.py ${{ inputs.version }}
               ../flatpak-flutter/flatpak-flutter.py --app-module wger flatpak-flutter.json
               git diff

      - name: Push updated config to flathub repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          destination-github-username: wger-project
          destination-repository-name: de.wger.flutter
          user-email: github-actions@github.com
          target-branch: release-${{ inputs.ref }}
          create-target-branch-if-needed: true
          commit-message: Update to ${{ inputs.ref }}

