name: Build release artefacts
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to tag and release (X.Y.Z)
        required: true
        type: string

jobs:

  build_apple:
    name: Apple
    uses: ./.github/workflows/build-apple.yml
    with:
      ref: ${{ github.event.inputs.version }}



